---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: creating the office-ssh security group
    local_action:
      module: ec2_group
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      name: office-ssh 
      description: group allowing inbound SSH conns from your Office 
      vpc_id: "{{ vpc.vpc_id }}"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ office_ip }}"
      rules_egress: 
        - proto: all
          from_port: 0
          to_port: 65535
          cidr_ip: 0.0.0.0/0
    register: office_ssh_sg_creation


  - name: creating the squid3 security group
    local_action:
      module: ec2_group
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      name: squid3 
      description: group holding the Squid3 instance 
      vpc_id: "{{ vpc.vpc_id }}"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 3128
          to_port: 3128
          cidr_ip: "{{ office_ip }}"
    register: squid_sg_creation


- include: ec2.yml  
