---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: creating the VPC
    local_action:
      module: ec2_vpc
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      cidr_block: 10.0.0.0/16
      dns_hostnames: yes
      dns_support: yes
      instance_tenancy: default
      internet_gateway: yes
      region: "{{ region }}"
      resource_tags: { "Environment": "Production" }
      route_tables:
        - subnets:
            - 10.0.0.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
      state: present
      subnets:
        - cidr: 10.0.0.0/24
          az: "{{ zone }}"
          resource_tags: { "Environment":"Production", "Name" : "Primary subnet" }
      wait: yes
    register: vpc


- include: secgroup.yml
